apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  sources:
    # 1️⃣ Chart source (Bitnami MongoDB)
    - chart: mongodb
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 15.1.3
      helm:
        valueFiles:
          - $values/Common/mongodb-values.yaml

    # 2️⃣ Values file source from Git repo
    - repoURL: 'https://github.com/maheshgowdamg/argocd1.git'
      targetRevision: HEAD
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

