architecture: replication

global:
  postgresql:
    auth:
      existingSecret: postgresql
      database: postgres
  storageClass: local-path

metrics:
  enabled: true
  pgStatStatements: true
  extendQuery: true
  # --- START: ADD THIS SECTION ---
  customMetrics:
    pg_stat_statements_slow_queries:
      query: |
        SELECT
          query,
          calls,
          mean_exec_time,
          total_exec_time
        FROM pg_stat_statements
        ORDER BY mean_exec_time DESC
        LIMIT 10
      metrics:
        - query:
            usage: "LABEL"
            description: "The query string"
        - calls:
            usage: "COUNTER"
            description: "Number of times the query has been executed"
        - mean_exec_time:
            usage: "GAUGE"
            description: "Mean execution time in milliseconds"
        - total_exec_time:
            usage: "GAUGE"
            description: "Total time spent in the statement in milliseconds"
  # --- END: ADD THIS SECTION ---

primary:
  extendedConfiguration: |
    max_connections = 3001
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all
    track_io_timing = on
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_connections = off
    log_disconnections = off
    log_min_duration_statement = 1000
    log_statement = 'all'
  persistence:
    size: 2Gi
  resourcesPreset: medium

readReplicas:
  replicaCount: 1
  extendedConfiguration: |
    max_connections = 3001
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all
    track_io_timing = on
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_connections = off
    log_disconnections = off
    log_min_duration_statement = 1000
    log_statement = 'all'
  persistence:
    size: 2Gi
  resourcesPreset: medium

replication:
  enabled: true
  numSynchronousReplicas: 1
  synchronousCommit: "on"
