architecture: replication

global:
  postgresql:
    auth:
      existingSecret: postgresql
      database: postgres
  storageClass: local-path

metrics:
  enabled: true
  pgStatStatements: true
  extendQuery: true
  customMetrics:
    queries: |-
      pg_stat_statements:
        query: |
          SELECT
            queryid,
            calls,
            total_exec_time,
            mean_exec_time,
            rows,
            LEFT(query, 200) AS query
          FROM pg_stat_statements
          WHERE calls > 0
          ORDER BY mean_exec_time DESC
          LIMIT 20;
        metrics:
          - queryid:
              usage: "LABEL"
              description: "Query ID"
          - query:
              usage: "LABEL"
              description: "Query text"
          - calls:
              usage: "COUNTER"
              description: "Number of times executed"
          - total_exec_time:
              usage: "GAUGE"
              description: "Total execution time (ms)"
          - mean_exec_time:
              usage: "GAUGE"
              description: "Mean execution time (ms)"
          - rows:
              usage: "GAUGE"
              description: "Rows retrieved/affected"

primary:
  extendedConfiguration: |
    max_connections = 3001
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all
    track_io_timing = on
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_min_duration_statement = 1000
    log_statement = 'all'
  persistence:
    size: 2Gi
  resourcesPreset: medium

readReplicas:
  replicaCount: 1
  extendedConfiguration: |
    max_connections = 3001
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all
    track_io_timing = on
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_min_duration_statement = 1000
    log_statement = 'all'
  persistence:
    size: 2Gi
  resourcesPreset: medium

replication:
  enabled: true
  numSynchronousReplicas: 1
  synchronousCommit: "on"
