architecture: replication

global:
  postgresql:
    auth:
      existingSecret: postgresql
      database: postgres


metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  pgStatStatements: true              # Enable pg_stat_statements collection

initdb:
  scripts:
    enable_pg_stat.sql: |
      CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
      CREATE USER exporter WITH PASSWORD 'DataDB@123';
      GRANT pg_monitor TO postgres;
      GRANT CONNECT ON DATABASE postgres TO postgres;
  

primary:
  extendedConfiguration: |
    max_connections = 3001
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all
    track_io_timing = on
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_min_duration_statement = 1000
    log_statement = 'all'
  persistence:
    size: 2Gi
  resourcesPreset: medium

readReplicas:
  replicaCount: 1
  extendedConfiguration: |
    max_connections = 3001
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all
    track_io_timing = on
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_min_duration_statement = 1000
    log_statement = 'all'
  persistence:
    size: 2Gi
  resourcesPreset: medium

replication:
  enabled: true
  numSynchronousReplicas: 1
  synchronousCommit: "on"
