architecture: replication
global:
  postgresql:
    auth:
      existingSecret: postgresql
      database: postgres
  storageClass: local-path
metrics:
  enabled: true
  pgStatStatements: true
  image:  # Add this to override the postgres-exporter image
    registry: docker.io
    repository: bitnami/postgres-exporter
    tag: 0.15.0  # Stable tag
primary:
  image:  # Add this to override the postgresql image for the primary
    registry: docker.io
    repository: bitnami/postgresql
    tag: 16.3.0  # Stable tag
  extendedConfiguration: |
    max_connections = 3001
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_connections = off
    log_disconnections = off
    log_min_duration_statement = 1000
    log_statement = 'all'
  persistence:
    size: 2Gi
  resourcesPreset: medium
readReplicas:
  image:  # Add this to override the postgresql image for replicas
    registry: docker.io
    repository: bitnami/postgresql
    tag: 16.3.0  # Stable tag
  replicaCount: 2
  extendedConfiguration: |
    max_connections = 3001
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_connections = off
    log_disconnections = off
    log_min_duration_statement = 1000
    log_statement = 'all'
  persistence:
    size: 2Gi
  resourcesPreset: medium
replication:
  enabled: true
  numSynchronousReplicas: 1
  synchronousCommit: "on"
