# postgresql-values.yaml

architecture: replication

global:
  postgresql:
    auth:
      existingSecret: postgresql
      database: postgres

metrics:
  enabled: true
  image:
    repository: bitnami/postgres-exporter
    tag: 0.15.0-debian-12-r36

primary:
  image:
    repository: bitnami/postgresql
    tag: 16.4.0-debian-12-r0  # updated working tag
  extendedConfiguration: |
    max_connections = 3001
    shared_preload_libraries = 'pg_stat_statements,pgaudit'
    pg_stat_statements.track = all
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_connections = off
    log_disconnections = off
    log_min_duration_statement = 1000
    log_statement = 'all'
  persistence:
    size: 2Gi
  resourcesPreset: small

readReplicas:
  replicaCount: 1
  image:
    repository: bitnami/postgresql
    tag: 16.4.0-debian-12-r0  # same as primary
  extendedConfiguration: |
    max_connections = 3001
    shared_preload_libraries = 'pg_stat_statements,pgaudit'
    pg_stat_statements.track = all
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_connections = off
    log_disconnections = off
    log_min_duration_statement = 1000
    log_statement = 'all'
  persistence:
    size: 2Gi
  resourcesPreset: small

replication:
  enabled: true
  numSynchronousReplicas: 1
  synchronousCommit: "on"
